# 注意
# 文字列はダブルクオーテーションで囲ってください
# sample = "サンプル"

# Chromeのパス(ChromeをCドライブ以外にインストールしているなど、特殊な状況のときに # を外して使用)
# chromePath = "D:\Program Files\Google\Chrome\Application\chrome.exe"

# 岩手県入札情報公開サービストップページ
topPage = "https://www.epi-cloud.fwd.ne.jp/koukai/do/KF001ShowAction?name1=0620060006600600"

# この業務名を含むものに絞る
projectTitle = "設計"

# ダウンロードする案件をNew(1週間以内)がついたものに限る (true or false)
downloadOnlyNew = true

# 1ページあたりの表示件数 (10, 25, 50, 100)
numberOfItems = 100

# このキーワードを含むPDFをダウンロードする
pdfKeywords = [
  "公告",
  "位置図",
  "図面",
  "参考資料",
  "平面図"
]

# ダウンロードされないファイルがある場合の調整項目
downloadTimeoutSec = 30                   # 案件ごとのダウンロードタイムアウト時間(秒)
pdfClickDelaySec = 3                      # PDFリンクのクリックのスリープ時間 (秒)

# Gmail送信機能設定
[mail]
sendEmailEnabled = false                # メール送信をするかどうか (true or false)
user = "example@gmail.com"              # Gamilのuser名(xxx@gmail.com)
pass = "yourapppassword"                # GoogleのAppパスワード
to = "example@gmail.com"                # 送信先メールアドレス(複数設定の例: "email1@example.com, email2@example.coom")

# debug用
[debug]
debugEnabled = false                  # debugモードを有効にする (true or flase)
headless = true                       # headlessモードを有効にする (true or false)